"""GitHub repo/branch catalog: worktree cloning, branch listing, repo fetching.

Extracted from slackbot.py to keep Slack message handling separate from
GitHub infrastructure.
"""

from __future__ import annotations

import base64
import hashlib
import logging
import re
import shutil
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Any
from urllib.parse import urlencode

import httpx

from app.config import get_settings
from app.services.github_repo import parse_repo_slug
from app.services.github_user_oauth import (
    resolve_github_user_access_token,
    resolve_github_user_login,
)
from app.services.repo_indexer_adapter import RepoIndexerError, get_repo_indexer_client

logger = logging.getLogger("feature_factory.branch_catalog")


# ---------------------------------------------------------------------------
# Exception
# ---------------------------------------------------------------------------

class GitHubAuthError(RuntimeError):
    """Raised when a saved GitHub OAuth connection exists but the token is no longer usable."""


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

STABLE_BASE_BRANCH_CANDIDATES = ("main", "master", "develop", "dev", "trunk")
BRANCH_WORKTREE_FETCH_TIMEOUT_SECONDS = 8
BRANCH_WORKTREE_CATALOG_ROOT = Path(tempfile.gettempdir()) / "prfactory_branch_catalog"
BRANCH_WORKTREE_PATH_NAME = "selection"
GITHUB_OPTION_CACHE_TTL_SECONDS = 120


# ---------------------------------------------------------------------------
# Caches
# ---------------------------------------------------------------------------

GITHUB_REPO_OPTIONS_CACHE: dict[str, tuple[float, list[str]]] = {}
GITHUB_BRANCH_OPTIONS_CACHE: dict[str, tuple[float, list[str]]] = {}
GITHUB_REPO_DEFAULT_BRANCH_CACHE: dict[str, tuple[float, str]] = {}
INDEXER_CATALOG_CACHE: dict[str, tuple[float, dict[str, Any]]] = {}


# ---------------------------------------------------------------------------
# Shared utilities
# ---------------------------------------------------------------------------

def dedupe(values: list[str]) -> list[str]:
    seen: set[str] = set()
    output: list[str] = []
    for raw in values:
        item = str(raw).strip()
        if not item:
            continue
        key = item.lower()
        if key in seen:
            continue
        seen.add(key)
        output.append(item)
    return output


def cache_key_for_user(*, user_id: str, team_id: str) -> str:
    return f"{(team_id or '').strip()}:{(user_id or '').strip()}"


# ---------------------------------------------------------------------------
# Branch naming helpers
# ---------------------------------------------------------------------------

def autogenerated_branch_prefixes(settings: Any) -> tuple[str, ...]:
    prefixes: list[str] = ["prfactory/"]
    configured = str(getattr(settings, "llm_push_branch_prefix", "") or "").strip().strip("/").lower()
    if configured:
        prefixes.append(f"{configured}/")
    unique: list[str] = []
    for item in prefixes:
        value = str(item or "").strip().lower()
        if not value:
            continue
        if value not in unique:
            unique.append(value)
    return tuple(unique)


def is_autogenerated_branch(settings: Any, branch_name: str) -> bool:
    normalized = str(branch_name or "").strip().lower()
    if not normalized:
        return False
    return any(normalized.startswith(prefix) for prefix in autogenerated_branch_prefixes(settings))


def stable_branch_fallback(
    settings: Any,
    *,
    branches: list[str],
    default_branch: str = "",
) -> str:
    normalized_default = str(default_branch or "").strip().lower()
    cleaned: list[str] = []
    seen: set[str] = set()
    for item in branches:
        branch = str(item or "").strip()
        if not branch:
            continue
        key = branch.lower()
        if key in seen:
            continue
        seen.add(key)
        cleaned.append(branch)
    if normalized_default and not is_autogenerated_branch(settings, normalized_default):
        return default_branch.strip()
    lower_to_actual = {item.lower(): item for item in cleaned}
    for candidate in STABLE_BASE_BRANCH_CANDIDATES:
        match = lower_to_actual.get(candidate)
        if match and not is_autogenerated_branch(settings, match):
            return match
    for branch in cleaned:
        lowered = branch.lower()
        if lowered == normalized_default:
            continue
        if not is_autogenerated_branch(settings, branch):
            return branch
    return ""


def normalize_branch_name(text: str) -> str:
    branch = str(text or "").splitlines()[0].strip()
    branch = branch.strip("`").strip()
    if branch.lower().startswith("refs/heads/"):
        branch = branch[11:].strip()
    return branch


# ---------------------------------------------------------------------------
# Git / GitHub low-level helpers
# ---------------------------------------------------------------------------

def github_api_headers(*, token: str) -> dict[str, str]:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def github_basic_auth_extraheader(token: str) -> str:
    raw = f"x-access-token:{token}".encode("utf-8")
    encoded = base64.b64encode(raw).decode("ascii")
    return f"AUTHORIZATION: basic {encoded}"


def run_git_command(*, cmd: list[str], cwd: Path, timeout_seconds: int) -> str:
    result = subprocess.run(
        cmd,
        cwd=str(cwd),
        capture_output=True,
        text=True,
        timeout=max(timeout_seconds, 1),
    )
    if result.returncode != 0:
        message = result.stderr.strip() or result.stdout.strip() or "git command failed"
        raise RuntimeError(message)
    return str(result.stdout or "").strip()


def branch_catalog_paths(*, owner: str, repo: str) -> tuple[Path, Path]:
    normalized = f"{owner.strip().lower()}/{repo.strip().lower()}"
    digest = hashlib.sha1(normalized.encode("utf-8")).hexdigest()[:12]
    owner_slug = re.sub(r"[^a-z0-9_.-]+", "-", owner.strip().lower()).strip("-") or "owner"
    repo_slug = re.sub(r"[^a-z0-9_.-]+", "-", repo.strip().lower()).strip("-") or "repo"
    root = BRANCH_WORKTREE_CATALOG_ROOT / f"{owner_slug}--{repo_slug}--{digest}"
    return root / "repo", root / BRANCH_WORKTREE_PATH_NAME


def remote_default_branch_from_git(*, repo_path: Path) -> str:
    try:
        raw = run_git_command(
            cmd=["git", "symbolic-ref", "refs/remotes/origin/HEAD"],
            cwd=repo_path,
            timeout_seconds=10,
        )
    except Exception:
        return ""
    marker = "refs/remotes/origin/"
    if raw.startswith(marker):
        return raw[len(marker) :].strip()
    return ""


def list_worktree_branches(*, repo_path: Path) -> list[str]:
    try:
        raw = run_git_command(
            cmd=["git", "worktree", "list", "--porcelain"],
            cwd=repo_path,
            timeout_seconds=10,
        )
    except Exception:
        return []

    branches: list[str] = []
    seen: set[str] = set()
    marker = "refs/heads/"
    for line in raw.splitlines():
        text = str(line or "").strip()
        if not text.startswith("branch "):
            continue
        value = text[len("branch ") :].strip()
        if value.startswith(marker):
            value = value[len(marker) :].strip()
        if not value:
            continue
        key = value.lower()
        if key in seen:
            continue
        seen.add(key)
        branches.append(value)
    return branches


def list_remote_branches_sorted_by_recent_commit(*, repo_path: Path) -> list[str]:
    try:
        raw = run_git_command(
            cmd=[
                "git",
                "for-each-ref",
                "refs/remotes/origin",
                "--sort=-committerdate",
                "--format=%(refname:short)",
            ],
            cwd=repo_path,
            timeout_seconds=20,
        )
    except Exception:
        return []

    branches: list[str] = []
    seen: set[str] = set()
    for line in raw.splitlines():
        value = str(line or "").strip()
        if not value.startswith("origin/"):
            continue
        name = value[len("origin/") :].strip()
        if not name or name == "HEAD":
            continue
        key = name.lower()
        if key in seen:
            continue
        seen.add(key)
        branches.append(name)
    return branches


# ---------------------------------------------------------------------------
# Branch sorting
# ---------------------------------------------------------------------------

def sort_branch_names_for_selection(
    settings: Any,
    *,
    branches: list[str],
    default_branch: str = "",
    worktree_branches: list[str] | None = None,
) -> list[str]:
    normalized_default = str(default_branch or "").strip().lower()
    worktree_set = {str(x or "").strip().lower() for x in (worktree_branches or []) if str(x or "").strip()}
    candidate_rank = {name: idx for idx, name in enumerate(STABLE_BASE_BRANCH_CANDIDATES)}

    cleaned: list[str] = []
    seen: set[str] = set()
    for item in branches:
        branch = str(item or "").strip()
        if not branch:
            continue
        key = branch.lower()
        if key in seen:
            continue
        seen.add(key)
        cleaned.append(branch)

    indexed = list(enumerate(cleaned))

    def _bucket(branch_name: str) -> tuple[int, int]:
        lowered = branch_name.lower()
        if lowered and lowered == normalized_default:
            return (0, 0)
        is_worktree = lowered in worktree_set
        is_generated = is_autogenerated_branch(settings, branch_name)
        stable_idx = candidate_rank.get(lowered)
        if is_worktree and not is_generated:
            return (1, 0)
        if stable_idx is not None and not is_generated:
            return (2, stable_idx)
        if not is_generated:
            return (3, 0)
        if is_worktree:
            return (4, 0)
        return (5, 0)

    indexed.sort(key=lambda pair: (*_bucket(pair[1]), pair[0], pair[1].lower()))
    return [item[1] for item in indexed]


# ---------------------------------------------------------------------------
# Worktree catalog
# ---------------------------------------------------------------------------

def fetch_branches_via_worktree_catalog(
    settings: Any,
    *,
    owner: str,
    repo: str,
    token: str,
    timeout_seconds: float,
) -> tuple[str, list[str]]:
    if shutil.which("git") is None:
        return "", []

    repo_path, selection_worktree = branch_catalog_paths(owner=owner, repo=repo)
    repo_path.parent.mkdir(parents=True, exist_ok=True)
    clone_url = f"https://github.com/{owner}/{repo}.git"
    auth_header = github_basic_auth_extraheader(token)
    timeout = max(int(timeout_seconds), 2)

    try:
        if not (repo_path / ".git").exists():
            if repo_path.exists():
                shutil.rmtree(repo_path, ignore_errors=True)
            run_git_command(
                cmd=[
                    "git",
                    "-c",
                    f"http.https://github.com/.extraheader={auth_header}",
                    "clone",
                    "--filter=blob:none",
                    "--depth",
                    "1",
                    "--no-single-branch",
                    "--no-checkout",
                    clone_url,
                    str(repo_path),
                ],
                cwd=repo_path.parent,
                timeout_seconds=timeout,
            )
        else:
            run_git_command(
                cmd=[
                    "git",
                    "-c",
                    f"http.https://github.com/.extraheader={auth_header}",
                    "fetch",
                    "--prune",
                    "--no-tags",
                    "--depth",
                    "1",
                    "origin",
                    "+refs/heads/*:refs/remotes/origin/*",
                ],
                cwd=repo_path,
                timeout_seconds=timeout,
            )
        try:
            run_git_command(
                cmd=[
                    "git",
                    "-c",
                    f"http.https://github.com/.extraheader={auth_header}",
                    "remote",
                    "set-head",
                    "origin",
                    "-a",
                ],
                cwd=repo_path,
                timeout_seconds=timeout,
            )
        except Exception:
            logger.exception("slack_github_branch_catalog_set_head_failed")
    except Exception as e:
        logger.warning(
            "slack_github_branch_catalog_sync_failed owner=%s repo=%s error=%s",
            owner,
            repo,
            e,
            exc_info=True,
        )
        return "", []

    default_branch = remote_default_branch_from_git(repo_path=repo_path)
    if default_branch:
        try:
            run_git_command(cmd=["git", "worktree", "prune"], cwd=repo_path, timeout_seconds=10)
        except Exception:
            logger.exception("slack_github_branch_catalog_worktree_prune_failed")
        # Keep one detached selection worktree per repo so branch selection can use git-worktree state.
        if not selection_worktree.exists():
            try:
                run_git_command(
                    cmd=[
                        "git",
                        "worktree",
                        "add",
                        "--detach",
                        str(selection_worktree),
                        f"origin/{default_branch}",
                    ],
                    cwd=repo_path,
                    timeout_seconds=20,
                )
            except Exception:
                logger.exception("slack_github_branch_catalog_worktree_seed_failed")

    raw_branches = list_remote_branches_sorted_by_recent_commit(repo_path=repo_path)
    worktree_branches = list_worktree_branches(repo_path=repo_path)
    sorted_branches = sort_branch_names_for_selection(
        settings,
        branches=raw_branches,
        default_branch=default_branch,
        worktree_branches=worktree_branches,
    )
    return default_branch, sorted_branches


# ---------------------------------------------------------------------------
# GitHub user token resolution
# ---------------------------------------------------------------------------

def resolve_github_user_token(*, user_id: str, team_id: str) -> str:
    token = resolve_github_user_access_token(slack_user_id=user_id, slack_team_id=team_id)
    if token or not (team_id or "").strip():
        return token
    # Fallback to user-wide token in case team scoping changed.
    return resolve_github_user_access_token(slack_user_id=user_id, slack_team_id="")


def github_connect_url_for_user(settings: Any, *, user_id: str, team_id: str = "") -> str:
    normalized_user = (user_id or "").strip()
    normalized_team = (team_id or "").strip()
    if settings.github_user_oauth_enabled() and normalized_user:
        return settings.github_oauth_install_url_for_user(
            slack_user_id=normalized_user,
            slack_team_id=normalized_team,
        )
    return settings.github_app_install_url_resolved()


def build_github_oauth_url(slack_user_id: str, slack_team_id: str = "") -> str:
    """Build the GitHub OAuth initiation URL for this Slack user."""
    settings = get_settings()
    url = github_connect_url_for_user(
        settings,
        user_id=(slack_user_id or "").strip(),
        team_id=(slack_team_id or "").strip(),
    )
    if url:
        return url
    base_url = (settings.base_url or "http://localhost:8000").strip().rstrip("/")
    params = {"slack_user_id": (slack_user_id or "").strip()}
    if (slack_team_id or "").strip():
        params["slack_team_id"] = (slack_team_id or "").strip()
    return f"{base_url}/api/github/install?{urlencode(params)}"


def github_user_connected(settings: Any, *, user_id: str, team_id: str) -> bool:
    if not settings.github_user_oauth_enabled():
        return True
    normalized_user = (user_id or "").strip()
    if not normalized_user:
        return False
    return bool(
        resolve_github_user_access_token(
            slack_user_id=normalized_user,
            slack_team_id=(team_id or "").strip(),
        )
    )


# ---------------------------------------------------------------------------
# Indexer helpers
# ---------------------------------------------------------------------------

def resolve_indexer_actor_id(*, user_id: str, team_id: str) -> str:
    login = resolve_github_user_login(slack_user_id=user_id, slack_team_id=team_id)
    if login:
        return login
    return str(user_id or "").strip()


def indexer_cache_key(
    *,
    user_id: str,
    team_id: str,
    actor_id: str,
    query: str,
    top_k_repos: int,
    top_k_branches_per_repo: int,
) -> str:
    query_token = str(query or "").strip().lower()
    return (
        f"{cache_key_for_user(user_id=user_id, team_id=team_id)}:"
        f"{actor_id.strip().lower()}:{query_token}:{int(top_k_repos)}:{int(top_k_branches_per_repo)}"
    )


def fetch_indexer_catalog_payload(
    settings: Any,
    *,
    user_id: str,
    team_id: str,
    query: str,
    top_k_repos: int,
    top_k_branches_per_repo: int,
    timeout_seconds: float = 2.5,
) -> dict[str, Any]:
    if not settings.repo_indexer_enabled():
        return {}
    actor_id = resolve_indexer_actor_id(user_id=user_id, team_id=team_id)
    if not actor_id:
        return {}

    cache_key = indexer_cache_key(
        user_id=user_id,
        team_id=team_id,
        actor_id=actor_id,
        query=query,
        top_k_repos=top_k_repos,
        top_k_branches_per_repo=top_k_branches_per_repo,
    )
    now = time.time()
    cached = INDEXER_CATALOG_CACHE.get(cache_key)
    if cached and (now - cached[0]) < GITHUB_OPTION_CACHE_TTL_SECONDS:
        return dict(cached[1] or {})

    indexer = get_repo_indexer_client(settings=settings)
    if indexer is None:
        return {}
    runtime_timeout = max(timeout_seconds, float(getattr(settings, "indexer_timeout_seconds", 0) or 0))
    indexer = indexer.__class__(
        base_url=indexer.base_url,
        auth_token=indexer.auth_token,
        timeout_seconds=max(runtime_timeout, 0.5),
    )

    try:
        payload = indexer.suggest_repos_and_branches(
            actor_id=actor_id,
            query=query,
            top_k_repos=max(int(top_k_repos), 1),
            top_k_branches_per_repo=max(int(top_k_branches_per_repo), 1),
        )
    except RepoIndexerError as e:
        logger.warning(
            "slack_indexer_catalog_suggest_failed actor=%s query=%s error=%s",
            actor_id,
            query,
            e,
        )
        return {}
    except Exception as e:  # noqa: BLE001
        logger.warning(
            "slack_indexer_catalog_suggest_failed actor=%s query=%s error=%s",
            actor_id,
            query,
            e,
            exc_info=True,
        )
        return {}

    if isinstance(payload, dict):
        INDEXER_CATALOG_CACHE[cache_key] = (now, payload)
        return payload
    return {}


def indexer_repo_slug(repo_payload: dict[str, Any]) -> str:
    full_name = str(repo_payload.get("full_name") or "").strip()
    if full_name:
        owner, repo = parse_repo_slug(full_name)
        if owner and repo:
            return f"{owner}/{repo}"
        return full_name
    owner = str(repo_payload.get("owner") or "").strip()
    name = str(repo_payload.get("name") or "").strip()
    if owner and name:
        return f"{owner}/{name}"
    return str(repo_payload.get("name") or repo_payload.get("id") or "").strip()


def indexer_repo_slugs(payload: dict[str, Any]) -> list[str]:
    repos: list[str] = []
    for item in payload.get("results") or []:
        if not isinstance(item, dict):
            continue
        repo_payload = item.get("repo")
        if not isinstance(repo_payload, dict):
            continue
        slug = indexer_repo_slug(repo_payload)
        if slug:
            repos.append(slug)
    return dedupe(repos)


def indexer_repo_suggestion_for_slug(payload: dict[str, Any], *, owner: str, repo: str) -> dict[str, Any]:
    target = f"{owner.strip().lower()}/{repo.strip().lower()}"
    fallback: dict[str, Any] = {}
    for item in payload.get("results") or []:
        if not isinstance(item, dict):
            continue
        repo_payload = item.get("repo")
        if not isinstance(repo_payload, dict):
            continue
        slug = indexer_repo_slug(repo_payload).strip().lower()
        if not slug:
            continue
        if slug == target:
            return item
        if not fallback and slug.endswith(f"/{repo.strip().lower()}"):
            fallback = item
    return fallback


def indexer_branch_names_and_default(
    settings: Any,
    *,
    suggestion: dict[str, Any],
) -> tuple[list[str], str]:
    repo_payload = suggestion.get("repo") if isinstance(suggestion, dict) else {}
    repo_payload = repo_payload if isinstance(repo_payload, dict) else {}
    default_branch = str(repo_payload.get("default_branch") or "").strip()
    branches: list[str] = []
    for item in suggestion.get("branches") or []:
        if not isinstance(item, dict):
            continue
        branch_name = str(item.get("name") or "").strip()
        if not branch_name:
            continue
        branches.append(branch_name)
        if not default_branch and bool(item.get("is_default")):
            default_branch = branch_name
    deduped = dedupe(branches)
    sorted_branches = sort_branch_names_for_selection(
        settings,
        branches=deduped,
        default_branch=default_branch,
        worktree_branches=[],
    )
    return sorted_branches, default_branch


def indexer_connect_url_for_user(
    settings: Any,
    *,
    user_id: str,
    team_id: str,
    timeout_seconds: float = 2.5,
) -> str:
    payload = fetch_indexer_catalog_payload(
        settings,
        user_id=user_id,
        team_id=team_id,
        query="",
        top_k_repos=1,
        top_k_branches_per_repo=1,
        timeout_seconds=timeout_seconds,
    )
    if not payload:
        return ""
    if not bool(payload.get("auth_required")):
        return ""
    return str(payload.get("connect_url") or "").strip()


# ---------------------------------------------------------------------------
# High-level fetch functions
# ---------------------------------------------------------------------------

def fetch_repositories_for_user(
    settings: Any,
    *,
    user_id: str,
    team_id: str,
    timeout_seconds: float = 2.5,
) -> list[str]:
    cache_key = cache_key_for_user(user_id=user_id, team_id=team_id)
    now = time.time()
    cached = GITHUB_REPO_OPTIONS_CACHE.get(cache_key)
    if cached and (now - cached[0]) < GITHUB_OPTION_CACHE_TTL_SECONDS:
        return list(cached[1])

    if settings.repo_indexer_enabled():
        indexer_payload = fetch_indexer_catalog_payload(
            settings,
            user_id=user_id,
            team_id=team_id,
            query="",
            top_k_repos=100,
            top_k_branches_per_repo=1,
            timeout_seconds=timeout_seconds,
        )
        indexer_repos = indexer_repo_slugs(indexer_payload)
        if indexer_repos:
            GITHUB_REPO_OPTIONS_CACHE[cache_key] = (now, indexer_repos)
            return list(indexer_repos)

    if not settings.github_user_oauth_enabled():
        return []
    token = resolve_github_user_token(user_id=user_id, team_id=team_id)
    if not token:
        return []

    repos: list[str] = []
    try:
        response = httpx.get(
            f"{settings.github_api_base.rstrip('/')}/user/repos",
            params={
                "per_page": 100,
                "sort": "updated",
                "affiliation": "owner,collaborator,organization_member",
            },
            headers=github_api_headers(token=token),
            timeout=timeout_seconds,
        )
        if response.status_code == 401:
            raise GitHubAuthError("GitHub OAuth token expired while loading repos.")
        response.raise_for_status()
        payload = response.json()
        if isinstance(payload, list):
            for item in payload:
                if not isinstance(item, dict):
                    continue
                full_name = str(item.get("full_name") or "").strip()
                owner, repo = parse_repo_slug(full_name)
                if owner and repo:
                    repos.append(f"{owner}/{repo}")
    except GitHubAuthError:
        raise
    except Exception as e:
        logger.warning(
            "slack_github_repo_fetch_failed user=%s team=%s url=%s error=%s",
            user_id,
            team_id,
            f"{settings.github_api_base.rstrip('/')}/user/repos",
            e,
            exc_info=True,
        )
        repos = []

    deduped = dedupe(repos)
    if deduped:
        GITHUB_REPO_OPTIONS_CACHE[cache_key] = (now, deduped)
    else:
        GITHUB_REPO_OPTIONS_CACHE.pop(cache_key, None)
    return deduped


def fetch_branches_for_repo(
    settings: Any,
    *,
    user_id: str,
    team_id: str,
    repo_slug: str,
    timeout_seconds: float = 2.5,
) -> list[str]:
    owner, repo = parse_repo_slug(repo_slug)
    if not owner or not repo:
        return []

    cache_key = f"{cache_key_for_user(user_id=user_id, team_id=team_id)}:{owner}/{repo}"
    now = time.time()
    cached = GITHUB_BRANCH_OPTIONS_CACHE.get(cache_key)
    if cached and (now - cached[0]) < GITHUB_OPTION_CACHE_TTL_SECONDS:
        return list(cached[1])

    if settings.repo_indexer_enabled():
        indexer_payload = fetch_indexer_catalog_payload(
            settings,
            user_id=user_id,
            team_id=team_id,
            query=f"{owner}/{repo}",
            top_k_repos=20,
            top_k_branches_per_repo=max(int(getattr(settings, "indexer_top_k_branches_per_repo", 8) or 8), 1),
            timeout_seconds=timeout_seconds,
        )
        suggestion = indexer_repo_suggestion_for_slug(indexer_payload, owner=owner, repo=repo)
        if suggestion:
            branches, default_branch = indexer_branch_names_and_default(settings, suggestion=suggestion)
            if branches:
                GITHUB_BRANCH_OPTIONS_CACHE[cache_key] = (now, list(branches))
                if default_branch:
                    GITHUB_REPO_DEFAULT_BRANCH_CACHE[cache_key] = (now, default_branch)
                return list(branches)

    if not settings.github_user_oauth_enabled():
        return []
    token = resolve_github_user_token(user_id=user_id, team_id=team_id)
    if not token:
        return []

    default_from_git, worktree_branches = fetch_branches_via_worktree_catalog(
        settings,
        owner=owner,
        repo=repo,
        token=token,
        timeout_seconds=max(timeout_seconds, BRANCH_WORKTREE_FETCH_TIMEOUT_SECONDS),
    )
    if worktree_branches:
        GITHUB_BRANCH_OPTIONS_CACHE[cache_key] = (now, list(worktree_branches))
        if default_from_git:
            GITHUB_REPO_DEFAULT_BRANCH_CACHE[cache_key] = (now, default_from_git)
        return list(worktree_branches)

    branches: list[str] = []
    try:
        response = httpx.get(
            f"{settings.github_api_base.rstrip('/')}/repos/{owner}/{repo}/branches",
            params={"per_page": 100},
            headers=github_api_headers(token=token),
            timeout=timeout_seconds,
        )
        if response.status_code == 401:
            raise GitHubAuthError("GitHub OAuth token expired while loading branches.")
        response.raise_for_status()
        payload = response.json()
        if isinstance(payload, list):
            for item in payload:
                if not isinstance(item, dict):
                    continue
                name = str(item.get("name") or "").strip()
                if name:
                    branches.append(name)
    except GitHubAuthError:
        raise
    except Exception as e:
        logger.warning(
            "slack_github_branch_fetch_failed user=%s team=%s repo=%s/%s error=%s",
            user_id,
            team_id,
            owner,
            repo,
            e,
            exc_info=True,
        )
        branches = []

    deduped = dedupe(branches)
    default_cached = str((GITHUB_REPO_DEFAULT_BRANCH_CACHE.get(cache_key) or (0.0, ""))[1] or "").strip()
    sorted_branches = sort_branch_names_for_selection(
        settings,
        branches=deduped,
        default_branch=default_cached,
        worktree_branches=[],
    )
    if sorted_branches:
        GITHUB_BRANCH_OPTIONS_CACHE[cache_key] = (now, sorted_branches)
    else:
        GITHUB_BRANCH_OPTIONS_CACHE.pop(cache_key, None)
    return sorted_branches


def fetch_default_branch_for_repo(
    settings: Any,
    *,
    user_id: str,
    team_id: str,
    repo_slug: str,
    timeout_seconds: float = 2.5,
) -> str:
    owner, repo = parse_repo_slug(repo_slug)
    if not owner or not repo:
        return ""

    cache_key = f"{cache_key_for_user(user_id=user_id, team_id=team_id)}:{owner}/{repo}"
    now = time.time()
    cached = GITHUB_REPO_DEFAULT_BRANCH_CACHE.get(cache_key)
    if cached and (now - cached[0]) < GITHUB_OPTION_CACHE_TTL_SECONDS:
        return str(cached[1] or "")

    if settings.repo_indexer_enabled():
        indexer_payload = fetch_indexer_catalog_payload(
            settings,
            user_id=user_id,
            team_id=team_id,
            query=f"{owner}/{repo}",
            top_k_repos=20,
            top_k_branches_per_repo=max(int(getattr(settings, "indexer_top_k_branches_per_repo", 8) or 8), 1),
            timeout_seconds=timeout_seconds,
        )
        suggestion = indexer_repo_suggestion_for_slug(indexer_payload, owner=owner, repo=repo)
        if suggestion:
            _branches, default_from_indexer = indexer_branch_names_and_default(settings, suggestion=suggestion)
            if default_from_indexer:
                GITHUB_REPO_DEFAULT_BRANCH_CACHE[cache_key] = (now, default_from_indexer)
                return default_from_indexer

    if not settings.github_user_oauth_enabled():
        return ""
    token = resolve_github_user_token(user_id=user_id, team_id=team_id)
    if not token:
        return ""

    default_from_git, worktree_branches = fetch_branches_via_worktree_catalog(
        settings,
        owner=owner,
        repo=repo,
        token=token,
        timeout_seconds=max(timeout_seconds, BRANCH_WORKTREE_FETCH_TIMEOUT_SECONDS),
    )
    if default_from_git:
        GITHUB_REPO_DEFAULT_BRANCH_CACHE[cache_key] = (now, default_from_git)
        if worktree_branches:
            GITHUB_BRANCH_OPTIONS_CACHE[cache_key] = (now, list(worktree_branches))
        return default_from_git

    default_branch = ""
    try:
        response = httpx.get(
            f"{settings.github_api_base.rstrip('/')}/repos/{owner}/{repo}",
            headers=github_api_headers(token=token),
            timeout=timeout_seconds,
        )
        if response.status_code == 401:
            raise GitHubAuthError("GitHub OAuth token expired while loading default branch.")
        response.raise_for_status()
        payload = response.json()
        if isinstance(payload, dict):
            default_branch = str(payload.get("default_branch") or "").strip()
    except GitHubAuthError:
        raise
    except Exception as e:
        logger.warning(
            "slack_github_default_branch_fetch_failed user=%s team=%s repo=%s/%s error=%s",
            user_id,
            team_id,
            owner,
            repo,
            e,
            exc_info=True,
        )
        default_branch = ""

    if default_branch:
        GITHUB_REPO_DEFAULT_BRANCH_CACHE[cache_key] = (now, default_branch)
    else:
        GITHUB_REPO_DEFAULT_BRANCH_CACHE.pop(cache_key, None)
    return default_branch
