from __future__ import annotations

from pathlib import Path

import pytest

import app.services.coderunner_adapter as coderunner_mod
from app.config import Settings


def test_prepare_target_repo_clone_uses_base_branch_when_provided(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    captured: dict[str, object] = {}

    def fake_run_command(
        cmd: list[str],
        *,
        cwd: Path,
        timeout_seconds: int = 600,
        env: dict[str, str] | None = None,
    ) -> str:
        captured["cmd"] = cmd
        captured["cwd"] = cwd
        return ""

    monkeypatch.setattr(coderunner_mod, "_run_command", fake_run_command)
    monkeypatch.setattr(coderunner_mod, "_github_basic_auth_header", lambda _token: "AUTHORIZATION: basic stub")

    target = tmp_path / "target"
    resolved = coderunner_mod._prepare_target_repo(
        target_path=target,
        owner="acme",
        repo="widgets",
        token="token",
        base_branch="develop",
    )

    cmd = captured["cmd"]
    assert isinstance(cmd, list)
    assert "--branch" in cmd
    branch_index = cmd.index("--branch")
    assert cmd[branch_index + 1] == "develop"
    assert resolved == "develop"


def test_prepare_target_repo_explicit_base_branch_skips_remote_resolution(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    captured: dict[str, object] = {}

    def fake_run_command(
        cmd: list[str],
        *,
        cwd: Path,
        timeout_seconds: int = 600,
        env: dict[str, str] | None = None,
    ) -> str:
        captured["cmd"] = cmd
        return ""

    monkeypatch.setattr(coderunner_mod, "_run_command", fake_run_command)
    monkeypatch.setattr(coderunner_mod, "_github_basic_auth_header", lambda _token: "AUTHORIZATION: basic stub")
    monkeypatch.setattr(
        coderunner_mod,
        "_remote_default_branch",
        lambda **_: (_ for _ in ()).throw(AssertionError("should not resolve remote default branch")),
    )
    monkeypatch.setattr(
        coderunner_mod,
        "_list_remote_heads",
        lambda **_: (_ for _ in ()).throw(AssertionError("should not list remote heads")),
    )

    target = tmp_path / "target"
    settings = Settings.model_construct(llm_push_branch_prefix="prfactory")
    resolved = coderunner_mod._prepare_target_repo(
        target_path=target,
        owner="acme",
        repo="widgets",
        token="token",
        base_branch="release/2026.02",
        settings=settings,
    )

    cmd = captured["cmd"]
    assert isinstance(cmd, list)
    assert "--branch" in cmd
    branch_index = cmd.index("--branch")
    assert cmd[branch_index + 1] == "release/2026.02"
    assert resolved == "release/2026.02"


def test_prepare_target_repo_returns_checked_out_branch_when_base_not_provided(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    calls: list[list[str]] = []

    def fake_run_command(
        cmd: list[str],
        *,
        cwd: Path,
        timeout_seconds: int = 600,
        env: dict[str, str] | None = None,
    ) -> str:
        calls.append(cmd)
        if cmd[:3] == ["git", "rev-parse", "--abbrev-ref"]:
            return "master"
        return ""

    monkeypatch.setattr(coderunner_mod, "_run_command", fake_run_command)
    monkeypatch.setattr(coderunner_mod, "_github_basic_auth_header", lambda _token: "AUTHORIZATION: basic stub")

    target = tmp_path / "target"
    resolved = coderunner_mod._prepare_target_repo(
        target_path=target,
        owner="acme",
        repo="widgets",
        token="token",
        base_branch="",
    )

    assert resolved == "master"
    assert any(cmd[:3] == ["git", "rev-parse", "--abbrev-ref"] for cmd in calls)


def test_prepare_target_repo_missing_base_branch_returns_clear_error(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    def fake_run_command(
        cmd: list[str],
        *,
        cwd: Path,
        timeout_seconds: int = 600,
        env: dict[str, str] | None = None,
    ) -> str:
        raise RuntimeError("fatal: Remote branch no-such-branch not found in upstream origin")

    monkeypatch.setattr(coderunner_mod, "_run_command", fake_run_command)
    monkeypatch.setattr(coderunner_mod, "_github_basic_auth_header", lambda _token: "AUTHORIZATION: basic stub")

    target = tmp_path / "target"
    with pytest.raises(RuntimeError) as exc:
        coderunner_mod._prepare_target_repo(
            target_path=target,
            owner="acme",
            repo="widgets",
            token="token",
            base_branch="no-such-branch",
        )

    message = str(exc.value)
    assert "does not exist" in message
    assert "no-such-branch" in message


def test_prepare_target_repo_uses_stable_fallback_for_autogenerated_default_branch(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    captured: dict[str, object] = {}

    def fake_run_command(
        cmd: list[str],
        *,
        cwd: Path,
        timeout_seconds: int = 600,
        env: dict[str, str] | None = None,
    ) -> str:
        captured["cmd"] = cmd
        return ""

    monkeypatch.setattr(coderunner_mod, "_run_command", fake_run_command)
    monkeypatch.setattr(coderunner_mod, "_github_basic_auth_header", lambda _token: "AUTHORIZATION: basic stub")
    monkeypatch.setattr(coderunner_mod, "_remote_default_branch", lambda **_: "prfactory/demo-123")
    monkeypatch.setattr(coderunner_mod, "_list_remote_heads", lambda **_: ["prfactory/demo-123", "main", "release/1.0"])

    target = tmp_path / "target"
    settings = Settings.model_construct(llm_push_branch_prefix="prfactory")
    resolved = coderunner_mod._prepare_target_repo(
        target_path=target,
        owner="acme",
        repo="widgets",
        token="token",
        base_branch="",
        settings=settings,
    )

    cmd = captured["cmd"]
    assert isinstance(cmd, list)
    assert "--branch" in cmd
    branch_index = cmd.index("--branch")
    assert cmd[branch_index + 1] == "main"
    assert resolved == "main"


def test_prepare_target_repo_allows_autogenerated_default_when_no_stable_fallback(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    def fake_run_command(
        cmd: list[str],
        *,
        cwd: Path,
        timeout_seconds: int = 600,
        env: dict[str, str] | None = None,
    ) -> str:
        if cmd[:3] == ["git", "rev-parse", "--abbrev-ref"]:
            return "prfactory/demo-123"
        return ""

    monkeypatch.setattr(coderunner_mod, "_run_command", fake_run_command)
    monkeypatch.setattr(coderunner_mod, "_github_basic_auth_header", lambda _token: "AUTHORIZATION: basic stub")
    monkeypatch.setattr(coderunner_mod, "_remote_default_branch", lambda **_: "prfactory/demo-123")
    monkeypatch.setattr(coderunner_mod, "_list_remote_heads", lambda **_: ["prfactory/demo-123"])

    target = tmp_path / "target"
    settings = Settings.model_construct(llm_push_branch_prefix="prfactory")
    resolved = coderunner_mod._prepare_target_repo(
        target_path=target,
        owner="acme",
        repo="widgets",
        token="token",
        base_branch="",
        settings=settings,
    )
    assert resolved == "prfactory/demo-123"


def test_resolve_pr_base_branch_returns_empty_when_unspecified() -> None:
    settings = Settings.model_construct(github_default_branch="main")
    resolved = coderunner_mod._resolve_pr_base_branch(spec={"base_branch": ""}, settings=settings)  # noqa: SLF001
    assert resolved == ""


def test_stable_branch_fallback_prefers_main() -> None:
    settings = Settings.model_construct(llm_push_branch_prefix="prfactory")
    value = coderunner_mod._stable_branch_fallback(  # noqa: SLF001
        settings=settings,
        branches=["prfactory/demo-123", "release/1.0", "main"],
        default_branch="prfactory/demo-123",
    )
    assert value == "main"


def test_stable_branch_fallback_uses_first_non_autogen_when_named_candidates_missing() -> None:
    settings = Settings.model_construct(llm_push_branch_prefix="prfactory")
    value = coderunner_mod._stable_branch_fallback(  # noqa: SLF001
        settings=settings,
        branches=["prfactory/demo-123", "release/2026.02", "prfactory/demo-124"],
        default_branch="prfactory/demo-123",
    )
    assert value == "release/2026.02"


def test_build_no_change_retry_prompt_mentions_attempt_context(tmp_path: Path) -> None:
    repo_path = tmp_path / "repo"
    repo_path.mkdir(parents=True, exist_ok=True)
    (repo_path / "app.py").write_text("print('hello')\n", encoding="utf-8")
    (repo_path / "README.md").write_text("# Demo\n", encoding="utf-8")

    prompt = coderunner_mod._build_no_change_retry_prompt(  # noqa: SLF001
        original_prompt="Base prompt",
        spec={
            "title": "Update greeting",
            "problem": "Change hello text",
            "acceptance_criteria": ["Greeting text is updated"],
        },
        repo_path=repo_path,
        attempt_number=2,
        total_attempts=2,
        previous_reply="No changes needed",
    )
    assert "produced no repository file changes" in prompt
    assert "attempt 1/2" in prompt
    assert "Greeting text is updated" in prompt


def test_branch_subject_uses_title_plus_short_feature_id() -> None:
    value = coderunner_mod._branch_subject(  # noqa: SLF001
        issue_number=0,
        feature_id="625c1cd5-baee-4ee4-a0e9-7d75534ae856",
        title="Build a quick welcome page",
    )
    assert value.startswith("build-a-quick-welcome-page")
    assert value.endswith("625c1cd5")


def test_repo_has_changes_detects_dirty_worktree(tmp_path: Path) -> None:
    repo = tmp_path / "repo-dirty"
    repo.mkdir(parents=True, exist_ok=True)
    coderunner_mod._run_command(["git", "init"], cwd=repo, timeout_seconds=30)  # noqa: SLF001
    coderunner_mod._run_command(["git", "config", "user.name", "test"], cwd=repo, timeout_seconds=30)  # noqa: SLF001
    coderunner_mod._run_command(["git", "config", "user.email", "test@example.com"], cwd=repo, timeout_seconds=30)  # noqa: SLF001
    (repo / "hello.txt").write_text("hello\n", encoding="utf-8")
    coderunner_mod._run_command(["git", "add", "-A"], cwd=repo, timeout_seconds=30)  # noqa: SLF001
    coderunner_mod._run_command(["git", "commit", "-m", "init"], cwd=repo, timeout_seconds=30)  # noqa: SLF001
    baseline = coderunner_mod._current_head_sha(repo_path=repo)  # noqa: SLF001

    (repo / "hello.txt").write_text("hello world\n", encoding="utf-8")
    has_changes, status, current_head = coderunner_mod._repo_has_changes(  # noqa: SLF001
        repo_path=repo,
        baseline_head=baseline,
    )
    assert has_changes is True
    assert status
    assert current_head == baseline


def test_repo_has_changes_detects_clean_precommitted_changes(tmp_path: Path) -> None:
    repo = tmp_path / "repo-precommit"
    repo.mkdir(parents=True, exist_ok=True)
    coderunner_mod._run_command(["git", "init"], cwd=repo, timeout_seconds=30)  # noqa: SLF001
    coderunner_mod._run_command(["git", "config", "user.name", "test"], cwd=repo, timeout_seconds=30)  # noqa: SLF001
    coderunner_mod._run_command(["git", "config", "user.email", "test@example.com"], cwd=repo, timeout_seconds=30)  # noqa: SLF001
    (repo / "hello.txt").write_text("hello\n", encoding="utf-8")
    coderunner_mod._run_command(["git", "add", "-A"], cwd=repo, timeout_seconds=30)  # noqa: SLF001
    coderunner_mod._run_command(["git", "commit", "-m", "init"], cwd=repo, timeout_seconds=30)  # noqa: SLF001
    baseline = coderunner_mod._current_head_sha(repo_path=repo)  # noqa: SLF001

    (repo / "hello.txt").write_text("hello world\n", encoding="utf-8")
    coderunner_mod._run_command(["git", "add", "-A"], cwd=repo, timeout_seconds=30)  # noqa: SLF001
    coderunner_mod._run_command(["git", "commit", "-m", "update"], cwd=repo, timeout_seconds=30)  # noqa: SLF001

    has_changes, status, current_head = coderunner_mod._repo_has_changes(  # noqa: SLF001
        repo_path=repo,
        baseline_head=baseline,
    )
    assert has_changes is True
    assert status == ""
    assert current_head and current_head != baseline
