from __future__ import annotations

from app.config import Settings
import app.slackbot as slackbot_mod
import app.services.branch_catalog as branch_catalog_mod
from app.slackbot import (
    IntakeSession,
    _action_root_message_ts,
    _branch_options_for_slack,
    _build_create_queue,
    _capture_field_answer,
    _create_spec_from_session,
    _finalize_create_session,
    _format_indexer_search_response_for_slack,
    _is_stop_command,
    _next_field,
    _post_prompt_confirmation_message,
    _process_session_message,
    _repo_selection_mutable,
    _repo_options_for_slack,
    _set_session_intake_mode,
)
from app.services.block_builders import (
    INTAKE_MODE_DEVELOPER,
    build_progress_text,
    developer_mode_repo_blocks,
    fallback_branch_options,
    feature_message_blocks,
    intake_mode_toggle_label,
    title_prompt_blocks,
)
from app.services.branch_catalog import (
    fetch_repositories_for_user,
    is_autogenerated_branch,
    sort_branch_names_for_selection,
    stable_branch_fallback,
)


def _dummy_session() -> IntakeSession:
    return IntakeSession(
        mode="create",
        feature_id="",
        user_id="U123",
        team_id="T123",
        channel_id="C123",
        thread_ts="1.0",
        message_ts="1.0",
    )


def test_build_create_queue_excludes_repo_when_not_required() -> None:
    queue = _build_create_queue(has_title=False, require_repo=False)
    assert "repo" not in queue


def test_build_create_queue_includes_repo_when_required() -> None:
    queue = _build_create_queue(has_title=False, require_repo=True)
    assert "implementation_mode" not in queue
    assert "edit_scope" not in queue
    assert "repo" in queue
    assert "base_branch" in queue


def test_capture_repo_requires_value_when_required() -> None:
    session = _dummy_session()
    ok, note = _capture_field_answer(
        session,
        field="repo",
        event={"text": "skip"},
        require_repo=True,
    )
    assert ok is False
    assert "required" in note.lower()


def test_capture_repo_accepts_org_repo() -> None:
    session = _dummy_session()
    ok, _note = _capture_field_answer(
        session,
        field="repo",
        event={"text": "acme/widgets"},
        require_repo=True,
    )
    assert ok is True
    assert session.answers["repo"] == "acme/widgets"


def test_capture_repo_accepts_repo_url_from_slack_markup() -> None:
    session = _dummy_session()
    ok, _note = _capture_field_answer(
        session,
        field="repo",
        event={"text": "<https://github.com/acme/widgets|widgets>"},
        require_repo=True,
    )
    assert ok is True
    assert session.answers["repo"] == "acme/widgets"


def test_next_field_skips_base_branch_in_normal_mode() -> None:
    session = _dummy_session()
    session.queue = ["repo", "base_branch"]
    session.answers["repo"] = "acme/widgets"
    session.queue.pop(0)
    assert _next_field(session) == ""


def test_next_field_keeps_base_branch_in_developer_mode() -> None:
    session = _dummy_session()
    _set_session_intake_mode(session, INTAKE_MODE_DEVELOPER)
    session.queue = ["base_branch"]
    session.answers["repo"] = "acme/widgets"
    assert _next_field(session) == "base_branch"


def test_next_field_skips_edit_scope_for_scratch_mode() -> None:
    session = _dummy_session()
    session.queue = ["edit_scope", "repo"]
    session.answers["implementation_mode"] = "new_feature"
    assert _next_field(session) == "repo"


def test_next_field_keeps_edit_scope_for_reuse_mode() -> None:
    session = _dummy_session()
    session.queue = ["edit_scope", "repo"]
    session.answers["implementation_mode"] = "reuse_existing"
    assert _next_field(session) == "edit_scope"


def test_capture_base_branch_validates_name() -> None:
    session = _dummy_session()
    ok, _ = _capture_field_answer(session, field="base_branch", event={"text": "main"})
    assert ok is True
    assert session.answers["base_branch"] == "main"


def test_capture_base_branch_normalizes_refs_heads_prefix() -> None:
    session = _dummy_session()
    ok, _ = _capture_field_answer(session, field="base_branch", event={"text": "refs/heads/release/1.0"})
    assert ok is True
    assert session.answers["base_branch"] == "release/1.0"


def test_create_spec_from_session_leaves_optional_fields_blank_when_missing() -> None:
    session = _dummy_session()
    session.answers = {
        "title": "Add invoice export",
        "repo": "acme/widgets",
    }
    spec = _create_spec_from_session(session)
    assert spec["problem"] == ""
    assert spec["business_justification"] == ""
    assert spec["acceptance_criteria"] == []


def test_create_spec_from_session_sets_default_edit_scope_for_reuse_mode() -> None:
    session = _dummy_session()
    session.answers = {
        "title": "Update welcome text",
        "implementation_mode": "reuse_existing",
        "repo": "acme/widgets",
    }
    spec = _create_spec_from_session(session)
    assert spec["source_repos"] == []
    assert "Focus on existing modules" in spec["edit_scope"]


def test_process_session_message_allows_cancel_while_awaiting_confirmation(monkeypatch) -> None:
    session = _dummy_session()
    session.answers["_awaiting_confirmation"] = True
    dropped: list[IntakeSession] = []
    posted: list[dict[str, object]] = []

    monkeypatch.setattr(slackbot_mod, "_drop_session", lambda candidate: dropped.append(candidate))

    class DummyClient:
        def chat_postMessage(self, **kwargs):
            posted.append(kwargs)

    _process_session_message(
        DummyClient(),
        slackbot_mod.logger,
        Settings.model_construct(),
        session,
        event={"text": "cancel", "files": []},
        user_id=session.user_id,
        team_id=session.team_id,
        channel_id=session.channel_id,
        thread_ts=session.thread_ts,
        text="cancel",
        subtype=None,
    )

    assert dropped == [session]
    assert posted[0]["text"] == "Intake cancelled. Use `/prfactory` to start again."


def test_process_session_message_starts_inline_edit_for_selected_field(monkeypatch) -> None:
    session = _dummy_session()
    session.answers["_editing_field"] = True
    stored: list[dict[str, object]] = []
    prompted: list[str] = []

    monkeypatch.setattr(slackbot_mod, "_store_session", lambda candidate: stored.append(dict(candidate.answers)))
    monkeypatch.setattr(slackbot_mod, "_ask_field_question", lambda _client, _session, *, field: prompted.append(field))

    class DummyClient:
        def chat_postMessage(self, **kwargs):
            return {"ok": True, "ts": "2.0"}

    _process_session_message(
        DummyClient(),
        slackbot_mod.logger,
        Settings.model_construct(),
        session,
        event={"text": "acceptance criteria", "files": []},
        user_id=session.user_id,
        team_id=session.team_id,
        channel_id=session.channel_id,
        thread_ts=session.thread_ts,
        text="acceptance criteria",
        subtype=None,
    )

    assert "_editing_field" not in session.answers
    assert session.answers["_editing_target_field"] == "acceptance_criteria"
    assert session.queue == ["acceptance_criteria"]
    assert prompted == ["acceptance_criteria"]
    assert stored[-1]["_editing_target_field"] == "acceptance_criteria"


def test_process_session_message_captures_inline_edit_answer_and_finalizes(monkeypatch) -> None:
    session = _dummy_session()
    session.answers = {
        "title": "Add export",
        "problem": "Old problem",
        "_editing_target_field": "problem",
    }
    session.queue = ["problem"]
    stored: list[dict[str, object]] = []
    finalized: list[dict[str, object]] = []
    posted: list[dict[str, object]] = []

    monkeypatch.setattr(slackbot_mod, "_store_session", lambda candidate: stored.append(dict(candidate.answers)))
    monkeypatch.setattr(slackbot_mod, "_finalize_session", lambda _client, _settings, candidate: finalized.append(dict(candidate.answers)))

    class DummyClient:
        def chat_postMessage(self, **kwargs):
            posted.append(kwargs)

    _process_session_message(
        DummyClient(),
        slackbot_mod.logger,
        Settings.model_construct(),
        session,
        event={"text": "New problem statement", "files": []},
        user_id=session.user_id,
        team_id=session.team_id,
        channel_id=session.channel_id,
        thread_ts=session.thread_ts,
        text="New problem statement",
        subtype=None,
    )

    assert session.answers["problem"] == "New problem statement"
    assert "_editing_target_field" not in session.answers
    assert session.queue == []
    assert any(item["text"] == "Captured." for item in posted)
    assert finalized[-1]["problem"] == "New problem statement"
    assert stored[-1]["problem"] == "New problem statement"


def testtitle_prompt_blocks_include_visible_question_and_hint() -> None:
    blocks = title_prompt_blocks(mode="normal")
    assert blocks[0]["type"] == "section"
    assert blocks[0]["text"]["text"] == "How can I help you?"
    assert blocks[1]["type"] == "context"
    assert "Enter what you want to build" in blocks[1]["elements"][0]["text"]


def testtitle_prompt_blocks_with_seed_prompt_asks_for_title() -> None:
    blocks = title_prompt_blocks(mode="normal", seed_prompt="Build a simple welcome page")
    assert blocks[0]["type"] == "section"
    assert blocks[0]["text"]["text"] == "What should this request be titled?"
    assert "Captured prompt" in blocks[1]["elements"][0]["text"]
    assert "Reply with a short title" in blocks[1]["elements"][1]["text"]


def test_repo_options_prompt_reconnect_when_saved_connection_missing_token(monkeypatch) -> None:
    settings = Settings.model_construct(
        enable_github_user_oauth=True,
        github_oauth_client_id="cid",
        github_oauth_client_secret="secret",
        github_repo_owner="",
        github_repo_name="",
    )
    monkeypatch.setattr(slackbot_mod, "resolve_github_user_token", lambda **_: "")
    monkeypatch.setattr(slackbot_mod, "has_github_user_connection", lambda **_: True)
    monkeypatch.setattr(slackbot_mod, "fetch_repositories_for_user", lambda *_, **__: [])

    options = _repo_options_for_slack(
        settings,
        user_id="U123",
        team_id="T123",
        query="",
    )

    assert any(opt["value"] == "__CONNECT__" for opt in options)
    assert any("Reconnect GitHub" in opt["text"]["text"] for opt in options)


def test_repo_options_use_query_candidate_for_github_url(monkeypatch) -> None:
    settings = Settings.model_construct(
        enable_github_user_oauth=False,
        github_repo_owner="",
        github_repo_name="",
    )
    monkeypatch.setattr(slackbot_mod, "resolve_github_user_token", lambda **_: "")
    monkeypatch.setattr(slackbot_mod, "has_github_user_connection", lambda **_: False)
    monkeypatch.setattr(slackbot_mod, "fetch_repositories_for_user", lambda *_, **__: [])

    options = _repo_options_for_slack(
        settings,
        user_id="U123",
        team_id="T123",
        query="https://github.com/acme/widgets",
    )

    assert any(opt["value"] == "acme/widgets" for opt in options)


def test_fetch_repositories_uses_indexer_catalog_when_enabled(monkeypatch) -> None:
    settings = Settings.model_construct(
        indexer_base_url="http://indexer-api:8080",
        enable_github_user_oauth=False,
    )
    branch_catalog_mod.GITHUB_REPO_OPTIONS_CACHE.clear()
    monkeypatch.setattr(
        branch_catalog_mod,
        "fetch_indexer_catalog_payload",
        lambda *_, **__: {
            "results": [
                {"repo": {"full_name": "acme/widgets"}},
                {"repo": {"owner": "foo", "name": "bar"}},
            ]
        },
    )

    repos = fetch_repositories_for_user(settings, user_id="U123", team_id="T123")

    assert repos == ["acme/widgets", "foo/bar"]
    branch_catalog_mod.GITHUB_REPO_OPTIONS_CACHE.clear()


def test_repo_options_offer_connect_when_indexer_requires_auth(monkeypatch) -> None:
    settings = Settings.model_construct(
        enable_github_user_oauth=False,
        github_repo_owner="",
        github_repo_name="",
        indexer_base_url="http://indexer-api:8080",
    )
    monkeypatch.setattr(slackbot_mod, "resolve_github_user_token", lambda **_: "")
    monkeypatch.setattr(slackbot_mod, "has_github_user_connection", lambda **_: False)
    monkeypatch.setattr(slackbot_mod, "fetch_repositories_for_user", lambda *_, **__: [])
    monkeypatch.setattr(slackbot_mod, "indexer_connect_url_for_user", lambda *_, **__: "https://indexer/connect")

    options = _repo_options_for_slack(
        settings,
        user_id="U123",
        team_id="T123",
        query="",
    )

    assert any(opt["value"] == "__CONNECT__" for opt in options)


def test_format_indexer_search_response_for_slack_includes_repo_and_evidence() -> None:
    payload = {
        "query": "retry logic",
        "results": [
            {
                "repo": {"full_name": "acme/widgets"},
                "score": 0.91,
                "evidence": [
                    {
                        "file_path": "src/retries.py",
                        "start_line": 10,
                        "end_line": 30,
                        "text": "retry wrapper checks for transient errors and requeues jobs",
                    }
                ],
            }
        ],
    }

    text = _format_indexer_search_response_for_slack(query="retry logic", payload=payload)

    assert "acme/widgets" in text
    assert "src/retries.py:10-30" in text
    assert "retry wrapper checks" in text


def test_developer_repo_blocks_use_static_select_options() -> None:
    options = [
        {"text": {"type": "plain_text", "text": "one"}, "value": "one/repo"},
        {"text": {"type": "plain_text", "text": "two"}, "value": "two/repo"},
    ]
    blocks = developer_mode_repo_blocks(options=options)
    accessory = blocks[0]["accessory"]
    assert accessory["type"] == "static_select"
    assert len(accessory["options"]) == 2


def testfallback_branch_options_prompts_for_existing_branch_name() -> None:
    options = fallback_branch_options()
    labels = [opt["text"]["text"] for opt in options]
    assert "Type existing base branch" in labels
    assert "Auto-create PRFactory branch (recommended)" in labels


def test_capture_source_repos_skip_allows_target_repo_only_in_reuse_mode() -> None:
    session = _dummy_session()
    session.answers["implementation_mode"] = "reuse_existing"
    ok, note = _capture_field_answer(session, field="source_repos", event={"text": "skip"})
    assert ok is True
    assert session.answers["source_repos"] == []
    assert "target repo context only" in note.lower()


def test_intake_mode_toggle_button_labels_show_action() -> None:
    assert intake_mode_toggle_label("normal") == "Switch to Developer"
    assert intake_mode_toggle_label("developer") == "Switch to Normal"


def test_is_stop_command_accepts_uppercase_and_punctuation() -> None:
    assert _is_stop_command("STOP") is True
    assert _is_stop_command(" stop! ") is True


def test_is_stop_command_rejects_non_command_text() -> None:
    assert _is_stop_command("stop alerts please") is False
    assert _is_stop_command("please stop") is False
    assert _is_stop_command("cancel") is False


def test_repo_selection_mutable_true_when_repo_is_current_field() -> None:
    session = _dummy_session()
    _set_session_intake_mode(session, INTAKE_MODE_DEVELOPER)
    session.queue = ["repo", "base_branch"]
    assert _repo_selection_mutable(session) is True


def test_repo_selection_mutable_true_when_base_branch_pending_in_developer_mode() -> None:
    session = _dummy_session()
    _set_session_intake_mode(session, INTAKE_MODE_DEVELOPER)
    session.queue = ["base_branch"]
    session.answers["repo"] = "acme/widgets"
    assert _repo_selection_mutable(session) is True


def test_repo_selection_mutable_stays_true_until_build_confirmation() -> None:
    session = _dummy_session()
    _set_session_intake_mode(session, INTAKE_MODE_DEVELOPER)
    session.queue = []
    session.answers["repo"] = "acme/widgets"
    session.answers["base_branch"] = "main"
    assert _repo_selection_mutable(session) is True


def test_create_spec_from_session_does_not_copy_seed_prompt_into_problem() -> None:
    session = _dummy_session()
    session.answers = {
        "title": "Welcome page",
        "_seed_prompt": "Build a quick welcome page with hello world text",
        "repo": "acme/widgets",
    }
    spec = _create_spec_from_session(session)
    assert spec["problem"] == ""


def testis_autogenerated_branch_uses_prefixes_from_settings() -> None:
    settings = Settings.model_construct(llm_push_branch_prefix="prfactory")
    assert is_autogenerated_branch(settings, "prfactory/demo-123") is True
    assert is_autogenerated_branch(settings, "main") is False


def test_branch_options_label_generated_branches(monkeypatch) -> None:
    settings = Settings.model_construct(llm_push_branch_prefix="prfactory")
    monkeypatch.setattr(slackbot_mod, "fetch_default_branch_for_repo", lambda *_, **__: "main")
    monkeypatch.setattr(
        slackbot_mod,
        "fetch_branches_for_repo",
        lambda *_, **__: ["main", "release/1.0", "prfactory/demo-123"],
    )

    options = _branch_options_for_slack(
        settings,
        user_id="U123",
        team_id="T123",
        repo_slug="acme/widgets",
        query="",
    )
    labels_by_value = {opt["value"]: opt["text"]["text"] for opt in options}
    assert labels_by_value["main"] == "Default: main"
    assert labels_by_value["release/1.0"] == "release/1.0"
    assert labels_by_value["prfactory/demo-123"] == "Bot branch: prfactory/demo-123"


def test_branch_options_default_autogen_shows_fallback_hint(monkeypatch) -> None:
    settings = Settings.model_construct(llm_push_branch_prefix="prfactory")
    monkeypatch.setattr(slackbot_mod, "fetch_default_branch_for_repo", lambda *_, **__: "prfactory/demo-123")
    monkeypatch.setattr(
        slackbot_mod,
        "fetch_branches_for_repo",
        lambda *_, **__: ["prfactory/demo-123", "main", "release/1.0"],
    )

    options = _branch_options_for_slack(
        settings,
        user_id="U123",
        team_id="T123",
        repo_slug="acme/widgets",
        query="",
    )
    labels_by_value = {opt["value"]: opt["text"]["text"] for opt in options}
    assert labels_by_value["prfactory/demo-123"] == "Default: prfactory/demo-123 (bot branch; fallback main)"


def test_branch_options_include_typed_branch_candidate(monkeypatch) -> None:
    settings = Settings.model_construct(llm_push_branch_prefix="prfactory")
    monkeypatch.setattr(slackbot_mod, "fetch_default_branch_for_repo", lambda *_, **__: "main")
    monkeypatch.setattr(
        slackbot_mod,
        "fetch_branches_for_repo",
        lambda *_, **__: ["main", "develop", "prfactory/demo-123"],
    )

    options = _branch_options_for_slack(
        settings,
        user_id="U123",
        team_id="T123",
        repo_slug="acme/widgets",
        query="feature/new-ui",
    )
    assert any(opt["value"] == "feature/new-ui" for opt in options)


def teststable_branch_fallback_uses_first_non_autogenerated_when_standard_missing() -> None:
    settings = Settings.model_construct(llm_push_branch_prefix="prfactory")
    fallback = stable_branch_fallback(
        settings,
        branches=["prfactory/demo-123", "release/2026.02"],
        default_branch="prfactory/demo-123",
    )
    assert fallback == "release/2026.02"


def testsort_branch_names_for_selection_prioritizes_default_then_stable_then_generated() -> None:
    settings = Settings.model_construct(llm_push_branch_prefix="prfactory")
    sorted_branches = sort_branch_names_for_selection(
        settings,
        branches=[
            "release/2026.02",
            "prfactory/demo-123",
            "develop",
            "main",
            "feature/new-ui",
        ],
        default_branch="develop",
    )
    assert sorted_branches == [
        "develop",
        "main",
        "release/2026.02",
        "feature/new-ui",
        "prfactory/demo-123",
    ]


def testsort_branch_names_for_selection_prioritizes_worktree_branches() -> None:
    settings = Settings.model_construct(llm_push_branch_prefix="prfactory")
    sorted_branches = sort_branch_names_for_selection(
        settings,
        branches=[
            "release/2026.02",
            "feature/one",
            "prfactory/demo-123",
            "prfactory/demo-456",
        ],
        default_branch="",
        worktree_branches=["feature/one", "prfactory/demo-456"],
    )
    assert sorted_branches == [
        "feature/one",
        "release/2026.02",
        "prfactory/demo-456",
        "prfactory/demo-123",
    ]


def test_post_prompt_confirmation_message_includes_run_build_button() -> None:
    captured: dict[str, object] = {}

    class DummyClient:
        def chat_postMessage(self, **kwargs):
            captured.update(kwargs)
            return {"ok": True}

    _post_prompt_confirmation_message(
        DummyClient(),
        channel_id="C123",
        thread_ts="1.0",
        feature_id="feature-123",
        original_request="Build a tiny page that says hello world",
        optimized_prompt="Build a tiny page",
    )
    blocks = captured["blocks"]
    assert isinstance(blocks, list)
    assert any("Original request" in str(block.get("text", {}).get("text", "")) for block in blocks if isinstance(block, dict))
    assert any("Optimized build prompt" in str(block.get("text", {}).get("text", "")) for block in blocks if isinstance(block, dict))
    action_blocks = [block for block in blocks if isinstance(block, dict) and block.get("type") == "actions"]
    assert action_blocks
    actions = action_blocks[0]["elements"]
    assert any(item.get("action_id") == "ff_run_build" for item in actions)
    assert any(item.get("action_id") == "ff_add_details" for item in actions)
    assert any(item.get("text", {}).get("text") == "Add more context" for item in actions)


def test_post_prompt_confirmation_message_adds_frontier_indicator_when_openrouter_enabled() -> None:
    captured: dict[str, object] = {}

    class DummyClient:
        def chat_postMessage(self, **kwargs):
            captured.update(kwargs)
            return {"ok": True}

    settings = Settings.model_construct(
        openrouter_api_key="sk-test",
        openrouter_frontier_model="anthropic/claude-opus-4-6",
    )

    _post_prompt_confirmation_message(
        DummyClient(),
        channel_id="C123",
        thread_ts="1.0",
        feature_id="feature-123",
        original_request="Build a tiny page that says hello world",
        optimized_prompt="Build a tiny page",
        settings=settings,
    )

    blocks = captured["blocks"]
    assert isinstance(blocks, list)
    context_blocks = [block for block in blocks if isinstance(block, dict) and block.get("type") == "context"]
    assert any("Analyzed by claude-opus-4-6" in str(block) for block in context_blocks)


def test_post_prompt_confirmation_message_omits_frontier_indicator_without_openrouter() -> None:
    captured: dict[str, object] = {}

    class DummyClient:
        def chat_postMessage(self, **kwargs):
            captured.update(kwargs)
            return {"ok": True}

    settings = Settings.model_construct(openrouter_api_key="")

    _post_prompt_confirmation_message(
        DummyClient(),
        channel_id="C123",
        thread_ts="1.0",
        feature_id="feature-123",
        original_request="Build a tiny page that says hello world",
        optimized_prompt="Build a tiny page",
        settings=settings,
    )

    blocks = captured["blocks"]
    assert isinstance(blocks, list)
    assert not any(
        "Analyzed by" in str(block)
        for block in blocks
        if isinstance(block, dict) and block.get("type") == "context"
    )


def testbuild_progress_text_empty_when_not_building() -> None:
    feature = {"status": "READY_FOR_BUILD"}
    assert build_progress_text(feature) == ""


def testfeature_message_blocks_show_runtime_and_refresh_when_building() -> None:
    feature = {
        "id": "feature-123",
        "status": "BUILDING",
        "title": "Build page",
        "created_at": "2026-02-25T10:00:00+00:00",
        "updated_at": "2026-02-25T10:02:00+00:00",
        "active_build_job_id": "job-1",
        "spec": {
            "implementation_mode": "new_feature",
            "repo": "acme/widgets",
            "_validation": {"missing": []},
        },
        "preview_url": "",
        "github_pr_url": "",
        "runs": [
            {
                "runner_run_id": "job-1",
                "status": "RUNNING",
                "started_at": "2026-02-25T10:00:00+00:00",
                "updated_at": "2026-02-25T10:05:00+00:00",
            }
        ],
        "events": [
            {"created_at": "2026-02-25T10:05:30+00:00"},
        ],
    }
    blocks = feature_message_blocks(feature, "http://localhost:8000")
    assert isinstance(blocks, list)
    context_elements = blocks[1]["elements"]
    assert any("Build runtime:" in str(item.get("text", "")) for item in context_elements)
    actions = blocks[2]["elements"]
    assert any(item.get("action_id") == "ff_refresh_status" for item in actions)


def test_action_root_message_ts_prefers_thread_ts() -> None:
    body = {"message": {"ts": "10.0", "thread_ts": "9.0"}}
    assert _action_root_message_ts(body) == "9.0"


def test_action_root_message_ts_falls_back_to_message_ts() -> None:
    body = {"message": {"ts": "10.0"}}
    assert _action_root_message_ts(body) == "10.0"


def test_create_spec_matches_user_branch_fallback_scenario() -> None:
    session = _dummy_session()
    session.answers = {
        "title": "My love",
        "_seed_prompt": 'I want to build a website that jsut has the text "I love you Rohan"',
        "implementation_mode": "new_feature",
        "repo": "TreyMangat/Slack_AI_Bot",
        "base_branch": "main",
    }
    spec = _create_spec_from_session(session)
    assert spec["title"] == "My love"
    assert spec["implementation_mode"] == "new_feature"
    assert spec["repo"] == "TreyMangat/Slack_AI_Bot"
    assert spec["base_branch"] == "main"
    assert spec["problem"] == ""


def test_finalize_create_session_continues_when_header_update_fails(monkeypatch) -> None:
    settings = Settings.model_construct(
        orchestrator_internal_url="http://api:8000",
        base_url="http://localhost:8000",
        slack_require_prompt_confirmation=True,
    )
    feature_payload = {
        "id": "c3cf60bb-77ba-4463-9313-60683c24fe97",
        "status": "READY_FOR_BUILD",
        "title": "My love",
        "spec": {
            "implementation_mode": "new_feature",
            "repo": "TreyMangat/Slack_AI_Bot",
            "base_branch": "main",
            "optimized_prompt": "Create a single-page site that renders only `I love you Rohan`.",
            "_validation": {"missing": []},
        },
        "preview_url": "",
        "github_pr_url": "",
    }

    class DummyResponse:
        def raise_for_status(self):
            return None

        def json(self):
            return feature_payload

    monkeypatch.setattr(slackbot_mod.httpx, "post", lambda *args, **kwargs: DummyResponse())
    monkeypatch.setattr(slackbot_mod, "_drop_session", lambda _session: None)
    monkeypatch.setattr(slackbot_mod, "_store_session", lambda _session: None)

    posted: list[dict[str, object]] = []

    class DummyClient:
        def chat_update(self, **kwargs):
            raise RuntimeError("update failed")

        def chat_postMessage(self, **kwargs):
            posted.append(kwargs)
            return {"ok": True, "ts": "2.0"}

    session = IntakeSession(
        mode="create",
        feature_id="",
        user_id="U123",
        team_id="T123",
        channel_id="C123",
        thread_ts="1.0",
        message_ts="1.0",
    )
    session.answers = {
        "title": "My love",
        "_seed_prompt": 'I want to build a website that jsut has the text "I love you Rohan"',
        "implementation_mode": "new_feature",
        "repo": "TreyMangat/Slack_AI_Bot",
        "base_branch": "main",
    }

    dummy_client = DummyClient()

    # First call posts spec summary for confirmation (no API call yet)
    _finalize_create_session(dummy_client, settings, session)
    texts_after_summary = [str(item.get("text") or "") for item in posted]
    assert any("review" in text.lower() or "summary" in text.lower() for text in texts_after_summary)

    # Simulate user clicking "Looks good, create it"
    session.answers["_spec_confirmed"] = True
    session.answers.pop("_awaiting_confirmation", None)
    posted.clear()

    _finalize_create_session(dummy_client, settings, session)

    texts = [str(item.get("text") or "") for item in posted]
    assert any("Created request" in text for text in texts)
    assert any("Build is paused for confirmation" in text for text in texts)
    assert any(
        any(
            element.get("action_id") == "ff_run_build"
            for block in block_set
            if isinstance(block, dict) and block.get("type") == "actions"
            for element in (block.get("elements") or [])
        )
        for block_set in [item.get("blocks") for item in posted if isinstance(item.get("blocks"), list)]
    )


def test_create_queue_minimal_has_no_implementation_mode():
    queue = _build_create_queue(has_title=False, require_repo=True, minimal=True)
    assert "implementation_mode" not in queue
    assert "edit_scope" not in queue
    assert "title" in queue
    assert "repo" in queue


def test_process_before_response_is_false():
    """process_before_response must be False to prevent Slack timeouts."""
    import pathlib

    source = pathlib.Path("orchestrator/app/slackbot.py").read_text()
    assert '"process_before_response": False' in source
